Try replacing #include <fp.h> with <math.h> to fix:
2025-09-01T23:22:49.3891250Z /Users/runner/build/ITK/Modules/ThirdParty/PNG/src/itkpng/pngpriv.h:527:16: fatal error: 'fp.h' file not found
2025-09-01T23:22:49.3992130Z   527 | #      include <fp.h>
2025-09-01T23:22:49.4092720Z       |                ^~~~~~

It seems to be missing now with Clang17